"use client";
import { FormEvent, useEffect, useState } from "react";
import { CheckCircle2, Save, ShieldCheck } from "lucide-react";
import { api } from "@/lib/api";

export default function ProfileEditor(){
  const[form,setForm]=useState<any>();const[msg,setMsg]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;api<any>("/creator/dashboard").then(response=>{if(active)setForm({name:response.profile.name,phone:response.profile.phone||"",email:response.profile.email,bio:response.profile.profile?.bio||"",portfolioUrl:response.profile.profile?.portfolioUrl||"",emailVerified:response.profile.emailVerified})}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:"Unable to load your profile")});return()=>{active=false}},[]);
  const set=(key:string,value:string)=>setForm((current:any)=>({...current,[key]:value}));
  const save=async(event:FormEvent)=>{event.preventDefault();setError("");setMsg("");setBusy(true);try{const response=await api<any>("/creator/profile",{method:"PATCH",body:JSON.stringify({name:form.name,phone:form.phone||null,bio:form.bio||null,portfolioUrl:form.portfolioUrl||null})});setForm((current:any)=>({...current,...response.profile,bio:response.profile.profile?.bio||"",portfolioUrl:response.profile.profile?.portfolioUrl||""}));setMsg("Profile saved")}catch(cause){setError(cause instanceof Error?cause.message:"Unable to save your profile")}finally{setBusy(false)}};
  const password=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setError("");setMsg("");setBusy(true);const formData=new FormData(event.currentTarget);try{const response=await api<{message:string}>("/creator/change-password",{method:"POST",body:JSON.stringify(Object.fromEntries(formData))});setMsg(response.message);event.currentTarget.reset()}catch(cause){setError(cause instanceof Error?cause.message:"Unable to update password")}finally{setBusy(false)}};
  return <div className="page"><div className="page-head"><div><div className="eyebrow">Account</div><h1>Your profile.</h1><p className="page-sub">Contact details, creator identity, portfolio, and account security.</p></div></div>{msg&&<div className="card" role="status" style={{background:"#e5eee5",marginBottom:20}}><CheckCircle2 size={18} color="var(--green)" aria-hidden="true"/> {msg}</div>}{error&&<div className="alert" role="alert">{error}</div>}<div className="detail-grid"><form className="form-card" onSubmit={save}>{!form?<div className="empty">Loading your profile…</div>:<><div className="eyebrow">Creator identity</div><h2>Public-facing details</h2><div className="field-grid"><label className="field"><span>Name</span><input value={form.name} onChange={event=>set("name",event.target.value)} required/></label><label className="field"><span>Email</span><input value={form.email} readOnly/><small className="hint">{form.emailVerified?"Verified":"Verification pending"}</small></label><label className="field"><span>Phone</span><input value={form.phone} onChange={event=>set("phone",event.target.value)} autoComplete="tel" placeholder="Optional"/></label><label className="field"><span>Portfolio URL</span><input type="url" value={form.portfolioUrl} onChange={event=>set("portfolioUrl",event.target.value)} placeholder="https://…"/></label><label className="field full"><span>Short bio</span><textarea value={form.bio} maxLength={1500} onChange={event=>set("bio",event.target.value)} placeholder="Tell reviewers about your creative practice."/></label></div><button className="button accent" disabled={busy}><Save size={15}/>{busy?"Saving…":"Save profile"}</button></>}</form><form className="form-card" onSubmit={password}><ShieldCheck size={24} aria-hidden="true"/><div className="eyebrow" style={{marginTop:18}}>Security</div><h2>Change password</h2><label className="field"><span>Current password</span><input name="currentPassword" type="password" minLength={8} maxLength={128} required autoComplete="current-password"/></label><label className="field"><span>New password</span><input name="newPassword" type="password" minLength={8} maxLength={128} required autoComplete="new-password"/></label><button className="button" disabled={busy}>{busy?"Updating…":"Update password"}</button></form></div></div>;
}
