"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";
import { Activity, Bell, BookOpen, FileText, HardDrive, Home, LogOut, MessageSquare, Plus, Search, Settings, UserRound, Users } from "lucide-react";
import { api } from "@/lib/api";

const creatorLinks = [{ href: "/creator", icon: Home, label: "Home" }, { href: "/creator/submissions", icon: BookOpen, label: "Work" }, { href: "/creator/submissions/new", icon: Plus, label: "Submit" }, { href: "/creator/profile/edit", icon: UserRound, label: "Profile" }];
const adminLinks = [{ href: "/admin", icon: Home, label: "Home" }, { href: "/admin/submissions", icon: FileText, label: "Reviews" }, { href: "/admin/creators", icon: Users, label: "Creators" }, { href: "/admin/files", icon: HardDrive, label: "Files" }, { href: "/admin/messages", icon: MessageSquare, label: "Messages" }, { href: "/admin/activity", icon: Activity, label: "Activity" }, { href: "/admin/settings", icon: Settings, label: "Settings" }];
export function AppShell({ children, role = "creator" }: { children: React.ReactNode; role?: "creator" | "admin" }) {
  const path = usePathname(); const router = useRouter(); const links = role === "admin" ? adminLinks : creatorLinks; const publicAdminLogin = role === "admin" && path === "/admin/login"; const [ready,setReady]=useState(publicAdminLogin); const [search,setSearch]=useState("");
  const activeHref = links.filter(link => path === link.href || path.startsWith(`${link.href}/`)).sort((a,b)=>b.href.length-a.href.length)[0]?.href;
  useEffect(()=>{let active=true;if(publicAdminLogin){setReady(true);return()=>{active=false}}setReady(false);api<{user:{role:string}}>("/auth/me").then(({user})=>{if(!active)return;if((role==="admin"&&user.role!=="ADMIN")||(role==="creator"&&user.role!=="CREATOR")){router.replace(user.role==="ADMIN"?"/admin":"/creator");return}setReady(true)}).catch(()=>{if(active)router.replace(role==="admin"?"/admin/login":"/login")});return()=>{active=false}},[role,router,publicAdminLogin]);
  const logout = async () => { try { await api("/auth/logout", { method: "POST" }); } finally { router.push(role === "admin" ? "/admin/login" : "/login"); router.refresh(); } };
  const searchWork = (event: FormEvent) => { event.preventDefault(); const query=search.trim(); if(!query)return; router.push(`${role === "admin" ? "/admin/submissions" : "/creator/submissions"}?q=${encodeURIComponent(query)}`); };
  if(publicAdminLogin) return <>{children}</>;
  if(!ready) return <div className="auth-panel" style={{minHeight:"calc(100vh - 44px)"}}><div className="empty">Opening your private workspace...</div></div>;
  return <div className="app-layout"><aside className="rail"><Link className="brand-mark" href="/" title="Public homepage" aria-label="Go to public homepage">S</Link><nav className="rail-links" aria-label="Private workspace navigation">{links.map(({ href, icon: Icon, label }) => <Link key={href} title={label} aria-label={label} aria-current={activeHref===href?"page":undefined} className={`rail-link ${activeHref === href ? "active" : ""}`} href={href}><Icon size={18}/></Link>)}</nav><button type="button" aria-label="Log out" title="Log out" className="rail-link" onClick={logout}><LogOut size={18}/></button></aside><main className="app-main"><header className="app-header"><Link className="workspace-home-link" href="/" aria-label="Back to StoryBoard homepage">StoryBoard <span>Public homepage</span></Link><form className="search" role="search" onSubmit={searchWork}><Search size={16} aria-hidden="true"/><input type="search" value={search} onChange={event=>setSearch(event.target.value)} aria-label={role === "admin" ? "Search submissions" : "Search your submissions"} placeholder={role === "admin" ? "Search submissions, creators, IDs…" : "Search your submissions…"}/></form><div className="user-chip"><Bell size={17} aria-hidden="true"/><span>{role === "admin" ? "Review desk" : "Creator studio"}</span><div className="avatar" aria-hidden="true">{role === "admin" ? "A" : "C"}</div></div></header>{children}</main><nav className="mobile-nav" aria-label="Mobile workspace navigation">{links.map(({ href,icon:Icon,label })=><Link key={href} href={href} aria-current={activeHref===href?"page":undefined}><Icon size={18}/>{label}</Link>)}</nav></div>;
}
