"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import { Download, Search } from "lucide-react";
import { api, date } from "@/lib/api";
import { useApiData } from "@/lib/useApiData";
import { Status } from "@/components/UI";

export default function Files(){const[q,setQ]=useState("");const[query,setQuery]=useState("");const[actionError,setActionError]=useState("");const{data,error,ready,reload}=useApiData<any>(`/admin/files?q=${encodeURIComponent(query)}`);const files=data?.files||[];const submit=(event:FormEvent)=>{event.preventDefault();setQuery(q.trim())};const download=async(id:string)=>{setActionError("");try{const response=await api<any>(`/files/${id}/download`);location.assign(response.url)}catch(cause){setActionError(cause instanceof Error?cause.message:"Unable to open this file")}};return <div className="page"><div className="page-head"><div><div className="eyebrow">Private media</div><h1>Files & uploads.</h1><p className="page-sub">Authorized access to creator documents, images, and video metadata.</p></div></div><form onSubmit={submit} className="filter-bar" role="search"><div className="search"><Search size={15} aria-hidden="true"/><input type="search" aria-label="Search files" value={q} onChange={event=>setQ(event.target.value)} placeholder="Search filename, title, or ID…"/></div><button className="button">Search</button></form>{(error||actionError)&&<div className="alert" role="alert">{error||actionError} {error&&<button type="button" className="text-button" onClick={reload}>Try again</button>}</div>}<div className="table-wrap" aria-busy={!ready}><table><thead><tr><th>File</th><th>Submission</th><th>Creator</th><th>Size</th><th>Status</th><th><span className="visually-hidden">Action</span></th></tr></thead><tbody>{!ready?<tr><td colSpan={6}>Loading files…</td></tr>:files.length?files.map((file:any)=><tr key={file.id}><td><strong>{file.originalName}</strong><br/><span className="hint">{file.mimeType} · {date(file.createdAt)}</span></td><td><Link href={`/admin/submissions/${file.submission.id}`}>{file.submission.publicSubmissionId||"Draft"}<br/><span className="hint">{file.submission.title}</span></Link></td><td>{file.submission.creator.name}</td><td>{(Number(file.sizeBytes)/1024/1024).toFixed(1)} MB</td><td><Status value={file.uploadStatus}/></td><td>{file.uploadStatus==="COMPLETE"&&<button type="button" className="button secondary" onClick={()=>download(file.id)}><Download size={14}/>Open</button>}</td></tr>):<tr><td colSpan={6}>{query?"No files match this search.":"No files have been uploaded."}</td></tr>}</tbody></table></div></div>}
